# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoUploader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
 
  # Pods for VideoUploader

  target 'VideoUploaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
